/**
 * Unoverse Design System Plugin
 * Definition-backed nodes (no React bundles).
 * AUTO-GENERATED by apps/unoverse/nodegen — do not edit manually
 */

import { createPlugin, type GravityPluginAPI } from "@unoverse-platform/plugin-base";
import packageJson from "../package.json";

import { AccountTransferWidgetNode } from "./AccountTransferWidget/node";
import { AIResponseNode } from "./AIResponse/node";
import { BarChartNode } from "./BarChart/node";
import { BarListNode } from "./BarList/node";
import { CardNode } from "./Card/node";
import { Card2Node } from "./Card2/node";
import { CardCarouselNode } from "./CardCarousel/node";
import { CardFinderNode } from "./CardFinder/node";
import { ImageBlockNode } from "./ImageBlock/node";
import { JourneyFinderNode } from "./JourneyFinder/node";
import { KenBurnsImageNode } from "./KenBurnsImage/node";
import { ListPickerNode } from "./ListPicker/node";
import { MarkdownRendererNode } from "./MarkdownRenderer/node";
import { MetricGridNode } from "./MetricGrid/node";
import { RadialGaugeNode } from "./RadialGauge/node";
import { StackedBarChartNode } from "./StackedBarChart/node";
import { StatCardNode } from "./StatCard/node";

const nodes = [
  AccountTransferWidgetNode,
  AIResponseNode,
  BarChartNode,
  BarListNode,
  CardNode,
  Card2Node,
  CardCarouselNode,
  CardFinderNode,
  ImageBlockNode,
  JourneyFinderNode,
  KenBurnsImageNode,
  ListPickerNode,
  MarkdownRendererNode,
  MetricGridNode,
  RadialGaugeNode,
  StackedBarChartNode,
  StatCardNode,
];

const plugin = createPlugin({
  name: packageJson.name,
  version: packageJson.version,
  description: packageJson.description,

  async setup(api: GravityPluginAPI) {
    const { setPlatformDependencies } = await import("@unoverse-platform/plugin-base");
    setPlatformDependencies({
      PromiseNode: api.classes.PromiseNode,
      CallbackNode: api.classes.CallbackNode,
      NodeInputType: api.types.NodeInputType,
      NodeConcurrency: api.types.NodeConcurrency,
      getNodeCredentials: api.getNodeCredentials,
      getConfig: api.getConfig,
      createLogger: api.createLogger,
      saveTokenUsage: api.saveTokenUsage,
      callService: api.callService,
      getRedisClient: api.getRedisClient,
      gravityPublish: api.gravityPublish,
      executeNodeWithRouting: api.executeNodeWithRouting,
      getAudioWebSocketManager: api.getAudioWebSocketManager,
    });

    for (const node of nodes) {
      api.registerNode(node);
    }
  },
});

export default plugin;
