/**
 * Unoverse Design System Plugin
 * Definition-backed nodes (no React bundles).
 * AUTO-GENERATED by apps/unoverse/nodegen — do not edit manually
 */

import { createPlugin, type GravityPluginAPI } from "@gravity-platform/plugin-base";
import packageJson from "../package.json";

import { CardNode } from "./Card/node";
import { Card2Node } from "./Card2/node";
import { CardCarouselNode } from "./CardCarousel/node";
import { ImageBlockNode } from "./ImageBlock/node";
import { KenBurnsImageNode } from "./KenBurnsImage/node";

const nodes = [
  CardNode,
  Card2Node,
  CardCarouselNode,
  ImageBlockNode,
  KenBurnsImageNode,
];

const plugin = createPlugin({
  name: packageJson.name,
  version: packageJson.version,
  description: packageJson.description,

  async setup(api: GravityPluginAPI) {
    const { setPlatformDependencies } = await import("@gravity-platform/plugin-base");
    setPlatformDependencies({
      PromiseNode: api.classes.PromiseNode,
      CallbackNode: api.classes.CallbackNode,
      NodeInputType: api.types.NodeInputType,
      NodeConcurrency: api.types.NodeConcurrency,
      getNodeCredentials: api.getNodeCredentials,
      getConfig: api.getConfig,
      createLogger: api.createLogger,
      saveTokenUsage: api.saveTokenUsage,
      callService: api.callService,
      getRedisClient: api.getRedisClient,
      gravityPublish: api.gravityPublish,
      executeNodeWithRouting: api.executeNodeWithRouting,
      getAudioWebSocketManager: api.getAudioWebSocketManager,
    });

    for (const node of nodes) {
      api.registerNode(node);
    }
  },
});

export default plugin;
