#!/usr/bin/env bash
# unoverse help

cmd_help() {
  echo ""
  echo -e "  ${BOLD}${CYAN}⬡ Unoverse Platform CLI${NC} ${DIM}v${GRAVITY_VERSION}${NC}"
  echo ""
  echo -e "  ${BOLD}Setup${NC}"
  echo -e "    ${GREEN}init${NC}        Interactive setup wizard"
  echo -e "    ${GREEN}doctor${NC}      Diagnose environment issues"
  echo ""
  echo -e "  ${BOLD}Platform${NC}"
  echo -e "    ${GREEN}start${NC}       Start all services"
  echo -e "    ${GREEN}stop${NC}        Stop all services"
  echo -e "    ${GREEN}status${NC}      Show service health"
  echo -e "    ${GREEN}check${NC}       Run full health check"
  echo -e "    ${GREEN}logs${NC}        Open the Dozzle log viewer ${DIM}(./unoverse logs <service> streams one in the terminal)${NC}"
  echo -e "    ${GREEN}update${NC}      Pull latest images and restart"
  echo -e "    ${GREEN}open${NC}        Open in browser ${DIM}(./unoverse open canvas|api|logs)${NC}"
  echo ""
  echo -e "  ${BOLD}Development${NC}"
  echo -e "    ${GREEN}dev${NC}         Install deps, gen nodes, start platform"
  echo -e "    ${GREEN}db-setup${NC}    Run database migrations ${DIM}(safe to re-run)${NC}"
  echo -e "    ${GREEN}db-verify${NC}   Verify database schema against Prisma"
  echo -e "    ${GREEN}build${NC}       Build and restart ${DIM}(./unoverse build <package>)${NC}"
  echo ""
  echo -e "  ${BOLD}Deployment${NC}"
  echo -e "    ${GREEN}deploy${NC}      Deploy to production VM ${DIM}(reads .env.production)${NC}"
  echo -e "    ${GREEN}deploy packages${NC}  Deploy carve-out + generate component nodes"
  echo -e "    ${GREEN}deploy db${NC}        Run database setup on server"
  echo -e "    ${GREEN}deploy marketplace${NC}  Reconcile prod's marketplace nodes against the DB"
  echo -e "    ${GREEN}deploy caddy${NC}     Install TLS reverse proxy"
  echo -e "    ${GREEN}deploy caddy-uninstall${NC}  Remove Caddy (revert to direct host ports)"
  echo -e "    ${GREEN}deploy umap${NC}      Install UMAP AI service"
  echo -e "    ${GREEN}deploy harden${NC}    Security hardening"
  echo -e "    ${GREEN}deploy test${NC}      Run connectivity test"
  echo ""
}
