#!/usr/bin/env bash
# unoverse help

cmd_help() {
  echo ""
  echo -e "  ${BOLD}${CYAN}⬡ Unoverse Platform CLI${NC} ${DIM}v${GRAVITY_VERSION}${NC}"
  echo ""
  echo -e "  ${BOLD}Setup${NC}"
  echo -e "    ${GREEN}init${NC}        Interactive setup wizard"
  echo -e "    ${GREEN}doctor${NC}      Diagnose environment issues"
  echo ""
  echo -e "  ${BOLD}Platform${NC}"
  echo -e "    ${GREEN}start${NC}       Start all services"
  echo -e "    ${GREEN}stop${NC}        Stop all services"
  echo -e "    ${GREEN}status${NC}      Show service health"
  echo -e "    ${GREEN}check${NC}       Run full health check"
  echo -e "    ${GREEN}logs${NC}        Open the Dozzle log viewer ${DIM}(./unoverse logs <service> streams one in the terminal)${NC}"
  echo -e "    ${GREEN}update${NC}      Pull latest images and restart"
  echo -e "    ${GREEN}open${NC}        Open in browser ${DIM}(./unoverse open canvas|api|logs)${NC}"
  echo ""
  echo -e "  ${BOLD}Development${NC}"
  echo -e "    ${GREEN}dev${NC}         Install deps, gen nodes, start platform"
  echo -e "    ${GREEN}db-setup${NC}    Run database migrations ${DIM}(safe to re-run)${NC}"
  echo -e "    ${GREEN}db-verify${NC}   Verify database schema against Prisma"
  echo -e "    ${GREEN}build${NC}       Build and restart ${DIM}(./unoverse build <package>)${NC}"
  echo ""
  echo -e "  ${BOLD}Design (rx/)${NC}"
  echo -e "    ${GREEN}new${NC}         Scaffold a definition ${DIM}(./unoverse new component <name> | new template <org> <name>)${NC}"
  echo -e "    ${GREEN}lint${NC}        Lint rx/ definitions ${DIM}(schema + guard rules)${NC}"
  echo ""
  echo -e "  ${BOLD}Deployment${NC}"
  echo -e "    ${GREEN}deploy${NC}          Deploy your platform: images + your work → your server"
  echo ""
  echo -e "  ${BOLD}Platform owner only${NC} ${DIM}(not shipped in the starter)${NC}"
  echo -e "    ${GREEN}publish${NC}         FULL RELEASE: guards → npm → tag vX.Y.Z (CI images) → starter sync"
  echo -e "    ${GREEN}publish a | b${NC}   Just the platform half / just the starter-kit half"
  echo -e "    ${GREEN}deploy design${NC}   Fast lane: rx/ definitions only — rsync + restart (no build)"
  echo -e "    ${GREEN}deploy init${NC}     First-time provisioning (install + carve-out)"
  echo -e "    ${GREEN}deploy db${NC}       Run database setup on server"
  echo -e "    ${GREEN}deploy caddy${NC}     Install TLS reverse proxy"
  echo -e "    ${GREEN}deploy caddy-uninstall${NC}  Remove Caddy (revert to direct host ports)"
  echo -e "    ${GREEN}deploy umap${NC}      Install UMAP AI service"
  echo -e "    ${GREEN}deploy harden${NC}    Security hardening"
  echo -e "    ${GREEN}deploy test${NC}      Run connectivity test"
  echo ""
}
